site_name: RingCentral Java SDK
theme:
    name: material
    features:
        - navigation.path
        - navigation.tabs
        - navigation.top
        - navigation.expand
        - navigation.sections
        - search.sharing
        - search.highlight
        - content.code.copy
        - content.action.edit
        - content.action.view
        - content.code.annotate
    palette:
        -   scheme: default
            primary: custom
            accent: indigo
            toggle:
                icon: material/toggle-switch
                name: Switch to dark mode
        -   scheme: slate
            primary: black
            accent: indigo
            toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono

    plugins:
        -   search:
                separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
        - badges
        - social
        -   exclude:
                regex:
                    - '^\.#.*'
                    - '.*\.\#.*$'
